/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import Traditions from "./Traditions";
import RulesOfBehavior from "./RulesOfBehavior";
import Footer from "./Footer";
import styles from "./AboutPage.module.css";

function AboutPage() {
  return (
    <div className={styles.aboutPage}>
    <main className={styles.container}>
        <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/2136e4ab8a63cb77c456a01609181cf5c8729a23ca44b27a280479770353f161?placeholderIfAbsent=true&apiKey=7b58294a66e9491ca1b54fe6e6c413c7"
        alt=""
        className={styles.backgroundImage}
      />
      <div className={styles.content}>
      <Header />
      <Hero />
      </div>
      </main>
      <Traditions />
      <RulesOfBehavior />
      <Footer />
      </div>
  );
}

export default AboutPage;
